from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

group = DefineGroup('kmulti_rtimer', src, depend = ['PKG_USING_KMULTI_RTIMER_DEMO'], CPPPATH = path)

Return('group')