from building import *
Import('rtconfig')

cwd = GetCurrentDir()
src	= Glob('*.c')
path = [cwd]

group = DefineGroup('multi_rtimer', src, depend = ['PKG_USING_MULTI_RTIMER_DEMO'], CPPPATH = path)

Return('group')